# Generated by Django 4.0.4 on 2022-05-14 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('privilege', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicLog',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('instru_id', models.IntegerField(default=1)),
                ('sentence', models.CharField(max_length=256)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('duration_time', models.FloatField(default=0.0)),
                ('file_path', models.CharField(default='-', max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privilege.user')),
            ],
            options={
                'db_table': 'lyrics_music',
            },
        ),
    ]
