# Generated by Django 4.0.4 on 2022-05-14 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('phone_number', models.CharField(default='-', max_length=16)),
                ('user_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lyrics_user',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('comment_sentence', models.CharField(default='该用户没有留下评论', max_length=256)),
                ('comment_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privilege.user')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
